name = input("Enter your name if you dare. ")
print("Good evening " + name)
bday = input("We cracked the code! Input your date of birth ")
print("We have figure out your birthday by hacking ur system hahaha it is " + bday)
SSN = input("if your SSN would be the amount of vbucks you had, how many would you have")
print("hacking system...")
print("haha! we found the code! " + SSN)